# Path for the git mirror directories
git_data_path = "/srv/git/"

# Path for checkouts of the git mirrors (optional)
# After pulling all remotes, local checkouts will be updated.
checkout_path = "/srv/git_checkout/"

# Suffix to use for naming repo directories (optional, default "")
checkout_suffix = ".git"

# Public URL of your cgit instance (optional)
cgit_url = "https://git.cpu.re/"

[github]
# Github auth token (optional)
#
# Github imposes rate limits on individual IPs unless they are
# authenticated with a token. The ratelimit is generous (60 requests
# per hour unauthenticated) so you shouldn't need to set this unless
# you're doing local development or monitoring really a lot of
# organizations for new repositories.
#
# https://developer.github.com/v3/#rate-limiting
token = "SECRET DON'T CHECK THIS IN ANYWHERE"

# List usernames (`"rahiel"`) or an organization (`"sunsistemo"`) to
# mirror all of their non-fork repositories.  Individual repos may be
# specified too as `owner/repo` (`"TeMPOraL/nyan-mode"`).
repositories = [
    "rahiel",
    "sunsistemo",
    "TeMPOraL/nyan-mode",
]

# Include arbitrary repositories with this pattern (1 [[repos]] block
# each):
#
#    [[repos]]
#    name = "repo-name"
#    owner = "owner"
#    description = "description"
#    homepage = "https://example.local"
#    clone_url = "https://git.example.local/owner/repo-name.git"
[[repos]]
name = "linux"
owner = "torvalds"
description = "Linux Kernel"
homepage = "https://kernel.org"
clone_url = "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
